# Generated by Django 5.1.4 on 2024-12-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description',  models.TextField()),
                ('developer', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('genres',  models.TextField()),
                ('release_date', models.DateField()),
                ('price_steam', models.FloatField()),
                ('rating', models.FloatField()),
                ('num_reviews', models.IntegerField()),
            ],
        ),
    ]
